export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LOGIN: "LoginScreen",
  REGISTER: "RegisterScreen",
  WELCOME: "WelcomeScreen",
  MESSAGES: "Messages",
  ACCOUNT: "Account",
  LISTING_EDIT: "ListingEdit",
  FEED: "Feed",
  LISTINGS: "Listings",
  PUBLIC_WORKS: "PublicWorks",
  PUBLIC_WORK_DETAILS: "PublicWorkDetails",
  PUBLIC_WORK_COLLECTS: "PublicWorkCollects",
  NEW_COLLECT: "NewCollect",
});
