export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LOGIN: "LoginScreen",
  REGISTER: "RegisterScreen",
  WELCOME: "WelcomeScreen",
  MESSAGES: "Messages",
  ACCOUNT: "Conta",
  LISTING_EDIT: "ListingEdit",
  FEED: "Feed",
  LISTINGS: "Listings",
  INSPECTIONS: "Vistorias",
  MAP: "Mapa",
  PUBLIC_WORKS: "Obras",
  PUBLIC_WORK_DETAILS: "PublicWorkDetails",
  PUBLIC_WORK_COLLECTS: "PublicWorkCollects",
  COLLECT_EDIT: "CollectEdit",
  GET_PHOTO: "GetPhoto",
});
