export default Object.freeze({
  LISTING_DETAILS: "ListingDetails",
  LOGIN: "LoginScreen",
  REGISTER: "RegisterScreen",
  WELCOME: "WelcomeScreen",
  MESSAGES: "Messages",
  ACCOUNT: "Account",
  LISTING_EDIT: "ListingEdit",
  PUBLIC_WORKS: "Feed",
  LISTINGS: "Listings",
  PUBLIC_WORKS: "PublicWorks",
  PUBLIC_WORK_DETAILS: "PublicWorkDetails",
  PUBLIC_WORK_COLLECTS: "PublicWorkCollects",
  COLLECT_EDIT: "CollectEdit",
  GET_PHOTO: "GetPhoto",
});
